name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  lock_threads:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'MDeLuise/plant-it' }}
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '14'
          issue-comment: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. If you have any update on this,
            please open a new issue.
          pr-inactive-days: '14'
          pr-comment: >
            This pull request has been automatically locked since there has not been
            any recent activity after it was closed. If you have any update on this,
            please open a new pull request.
          discussion-inactive-days: '14'
          discussion-comment: >
            This discussion has been automatically locked since there has not been
            any recent activity after it was closed. If you have any update on this,
            please open a discussion.
